language: rust
dist: bionic
os: 
  - linux
  - osx
  - windows
addons:
    apt:
        packages:
            - libssl-dev
            - libssh-dev
cache: cargo
rust:
  - stable
before_script: |
  CODECOV_TOKEN="c4972349-4171-46d9-b84a-4a3a0b4d86e7"
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi
script:
- cargo clean
- CARGO_INCREMENTAL=0 RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Coverflow-checks=off -Zno-landing-pads" cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi