language: rust
sudo: required
dist: bionic
os: 
  - linux
addons:
    apt:
        packages:
            - libssl-dev
            - libssh-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi
script:
  - export CODECOV_TOKEN="c4972349-4171-46d9-b84a-4a3a0b4d86e7"
  - export RUSTFLAGS="-Ccodegen-units=1 -Cinline-threshold=0 -Coverflow-checks=off"
  - cargo clean
  - cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
