language: rust
sudo: required
dist: bionic
os: 
  - linux
  - xos
  - windows
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - export CODECOV_TOKEN="c4972349-4171-46d9-b84a-4a3a0b4d86e7"
  - export CARGO_INCREMENTAL=0
  - RUSTFLAGS="-Ccodegen-units=1 -Cinline-threshold=0 -Coverflow-checks=off"
  - cargo clean
  - cargo build
  - ./test.sh
