[package]
name = "service"
version = "0.1.0"
authors = ["xiao.huang@enmotech.com <xiao.huang@enmotech.com>"]
edition = "2018"

[target."cfg(windows)".dependencies]
windows-service = "*"

[target."cfg(niux)".dependencies]
daemonize = "*"
ctrlc = "*"
nix= "*"
users = "0.10"
signal-hook = "0.1.15"