[package]
name = "bee-codegen"
version = "0.1.0"
authors = ["xiao.huang@enmotech.com <xiao.huang@enmotech.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "fold","parsing"] }
quote = "1.0"
proc-macro2 = "*"