//! `bee-registry::loader` — S33: load a plugin from a `.so` / `.dylib` /
//! `.dll` via `libloading`.
//!
//! This is the **real** plugin-loading path, complementing the
//! in-process `Plugin` trait (which is used by tests + the
//! S19 MVP path). The S19 `PluginManager::register` takes raw
//! bytes + a manifest; `register_library` here opens the
//! `cdylib`, calls the `bee_plugin_init` symbol, and reuses the
//! same ABI / identity check.
//!
//! ## ABI / ownership
//!
//! The `bee_plugin_init` symbol is generated by
//! [`bee_plugin_sdk::cdylib_plugin!`] and follows the contract:
//!
//! - `init(host: *mut BeeHostV1) -> *mut PluginHandle`
//!   - `host` is currently unused by S33 mock plugins (we pass
//!     `null_mut()`); the S19+ follow-up that calls back into the
//!     host for `register_adapter` will thread a real `BeeHostV1`
//!     through.
//!   - On success, returns a non-null `*mut PluginHandle` produced
//!     by `Arc::into_raw(Arc::new(handle))`.
//!   - On error, returns null.
//! - `drop(handle: *mut PluginHandle)` is generated as the inverse:
//!   `Arc::from_raw(handle)`. The host calls this when the
//!   `LoadedPlugin` is dropped (S19+ follow-up; the S33 path keeps
//!   the `Library` alive in `LoadedPlugin._lib`).
//!
//! The `LoadedPlugin` owns both the `Arc<PluginHandle>` and the
//! `Library`. When `LoadedPlugin` drops, the library is unloaded
//! (the OS reclaims the `.so`); the `Arc<PluginHandle>` is dropped
//! last via the `Arc::from_raw` produced by the plugin.

use std::path::Path;
use std::sync::Arc;

use bee_plugin_sdk::{
    compute_plugin_id, AbiVersion, BeeHostV1, PluginError, PluginHandle, PluginId, PluginManifest,
    PluginResult,
};
use libloading::{Library, Symbol};

use crate::PluginManager;

/// A plugin loaded from a `cdylib` on disk.
///
/// Owns the [`Library`] (which keeps the `.so` / `.dylib` mapped
/// in memory) and the [`Arc<PluginHandle>`] (the plugin's
/// registered metadata + state). Drop in either order is safe;
/// `LoadedPlugin` is the natural lifetime boundary.
pub struct LoadedPlugin {
    pub id: PluginId,
    pub handle: Arc<PluginHandle>,
    /// The OS handle for the loaded library. Held only to keep
    /// the library mapped while `handle` is alive.
    _lib: Library,
}

impl LoadedPlugin {
    /// The plugin's identity (sha256 of the binary content).
    pub fn id(&self) -> &PluginId {
        &self.id
    }

    /// The plugin's reported manifest (Adapters, Handlers, etc.).
    pub fn manifest(&self) -> &PluginManifest {
        &self.handle.manifest
    }
}

/// Load a `cdylib` plugin from disk.
///
/// Steps:
/// 1. Read the file (for `PluginId` derivation).
/// 2. Open the library with `libloading::Library::new`.
/// 3. Resolve the `bee_plugin_init` symbol.
/// 4. Call it with a null `BeeHostV1` (S33 mock plugins don't call
///    back into the host; the FFI surface is reserved for
///    follow-ups).
/// 5. Wrap the returned `*mut PluginHandle` in an `Arc`.
///
/// # Errors
/// - I/O error reading the file → `PluginError::Init`
/// - `libloading` error opening the library → `PluginError::Init`
/// - Missing `bee_plugin_init` symbol → `PluginError::Init`
/// - Plugin's `init()` returned null (init failed) →
///   `PluginError::Init`
pub fn load_library<P: AsRef<Path>>(path: P) -> PluginResult<LoadedPlugin> {
    let path = path.as_ref();
    let content = std::fs::read(path).map_err(|e| {
        PluginError::Init(format!("read {}: {e}", path.display()))
    })?;
    let id = compute_plugin_id(&content);

    unsafe {
        let lib = Library::new(path).map_err(|e| {
            PluginError::Init(format!("dlopen {}: {e}", path.display()))
        })?;
        let init: Symbol<
            unsafe extern "C" fn(*mut BeeHostV1) -> *mut PluginHandle,
        > = lib.get(b"bee_plugin_init").map_err(|e| {
            PluginError::Init(format!(
                "missing bee_plugin_init in {}: {e}",
                path.display()
            ))
        })?;
        let handle_ptr = init(std::ptr::null_mut());
        if handle_ptr.is_null() {
            return Err(PluginError::Init(format!(
                "{}: bee_plugin_init returned null",
                path.display()
            )));
        }
        let handle = Arc::from_raw(handle_ptr);
        Ok(LoadedPlugin {
            id,
            handle,
            _lib: lib,
        })
    }
}

/// ABI compatibility check (S20). Returns `Ok(())` if the plugin's
/// declared `abi_version` is in the host's accepted majors.
///
/// Convenience for callers that want to do the check **before**
/// adding the plugin to the `PluginManager`. The
/// `PluginManager::register_library` does the same check
/// internally.
pub fn check_abi(
    manifest: &PluginManifest,
    accepted_majors: &[u32],
) -> PluginResult<()> {
    let abi = AbiVersion::parse(&manifest.abi_version)?;
    if !abi.matches_major(accepted_majors) {
        return Err(PluginError::AbiMismatch {
            hash: "(unknown — pre-load)".into(),
            claimed: manifest.abi_version.clone(),
            expected: accepted_majors.to_vec(),
            migration_link: bee_plugin_sdk::MIGRATION_DOC_LINK.to_string(),
        });
    }
    Ok(())
}

/// Walk `dir` (non-recursive) and `register_library` every file
/// with the platform's dynamic-library extension
/// (`.so`/`.dylib`/`.dll`). Returns the loaded `PluginId`s in
/// directory-iteration order.
///
/// Errors from individual files (bad ABI, missing symbol, etc.)
/// are collected into the returned `Vec<PluginError>` — one
/// entry per failure. The caller can decide whether to abort or
/// continue. Successfully-loaded plugins are registered with
/// the `PluginManager` regardless of the per-file errors.
///
/// An empty directory (or a directory that contains no files
/// with the dynamic-library extension) returns
/// `(vec![], vec![])` — no error, no load. A missing directory
/// returns an `Init` error describing the read failure.
pub fn load_directory(
    pm: &mut PluginManager,
    dir: &Path,
) -> (Vec<PluginId>, Vec<PluginError>) {
    let mut loaded = vec![];
    let mut errors = vec![];
    let entries = match std::fs::read_dir(dir) {
        Ok(it) => it,
        Err(e) => {
            errors.push(PluginError::Init(format!(
                "read_dir {}: {e}",
                dir.display()
            )));
            return (loaded, errors);
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        let is_lib = matches!(ext, "so" | "dylib" | "dll");
        if !is_lib {
            continue;
        }
        match pm.register_library(&path) {
            Ok(id) => loaded.push(id),
            Err(e) => errors.push(e),
        }
    }
    (loaded, errors)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn check_abi_accepts_v1() {
        let m = PluginManifest {
            name: bee_plugin_sdk::PluginName("test".into()),
            feature_version: "1.0.0".into(),
            abi_version: "v1".into(),
            adapters: vec![],
            handlers: vec![],
        };
        assert!(check_abi(&m, &[1]).is_ok());
        assert!(check_abi(&m, &[1, 2]).is_ok());
        assert!(check_abi(&m, &[2]).is_err());
    }

    #[test]
    fn check_abi_rejects_garbage_version() {
        let m = PluginManifest {
            name: bee_plugin_sdk::PluginName("test".into()),
            feature_version: "1.0.0".into(),
            abi_version: "garbage".into(),
            adapters: vec![],
            handlers: vec![],
        };
        let err = check_abi(&m, &[1]).unwrap_err();
        assert!(matches!(err, PluginError::InvalidAbiVersion(_)));
    }

    #[test]
    fn load_missing_file_errors() {
        let result = load_library("/tmp/this_does_not_exist_xyz.so");
        assert!(matches!(result, Err(PluginError::Init(_))));
    }

    #[test]
    fn load_directory_on_empty_dir_returns_no_errors() {
        let dir = tempfile::tempdir().unwrap();
        let mut pm = crate::PluginManager::new();
        let (loaded, errors) = load_directory(&mut pm, dir.path());
        assert!(loaded.is_empty(), "empty dir must not load anything");
        assert!(errors.is_empty(), "empty dir must not produce errors");
    }
}
