//! `bee-registry::loader` — S33: load a plugin from a `.so` / `.dylib` /
//! `.dll` via `libloading`.
//!
//! This is the **real** plugin-loading path, complementing the
//! in-process `Plugin` trait (which is used by tests + the
//! S19 MVP path). The S19 `PluginManager::register` takes raw
//! bytes + a manifest; `register_library` here opens the
//! `cdylib`, calls the `bee_plugin_init` symbol, and reuses the
//! same ABI / identity check.
//!
//! ## ABI / ownership
//!
//! The `bee_plugin_init` symbol is generated by
//! [`bee_plugin_sdk::cdylib_plugin!`] and follows the contract:
//!
//! - `init(host: *mut BeeHostV1) -> *mut PluginHandle`
//!   - `host` is a real `BeeHostV1` whose function pointers are
//!     populated by [`build_demo_host`]. S33 mock plugins ignore
//!     the host entirely; the S41 perf-fib plugin uses the new
//!     `kv_get` / `kv_put` / `kv_cas` / `current_stream_id`
//!     slots for KV-backed state.
//!   - On success, returns a non-null `*mut PluginHandle` produced
//!     by `Arc::into_raw(Arc::new(handle))`.
//!   - On error, returns null.
//! - `drop(handle: *mut PluginHandle)` is generated as the inverse:
//!   `Arc::from_raw(handle)`. The host calls this when the
//!   `LoadedPlugin` is dropped (S19+ follow-up; the S33 path keeps
//!   the `Library` alive in `LoadedPlugin._lib`).
//!
//! The `LoadedPlugin` owns both the `Arc<PluginHandle>` and the
//! `Library`. When `LoadedPlugin` drops, the library is unloaded
//! (the OS reclaims the `.so`); the `Arc<PluginHandle>` is dropped
//! last via the `Arc::from_raw` produced by the plugin.
//!
//! ## S41 host-side wiring
//!
//! As of S41 Task 3, [`load_library`] constructs a real
//! `BeeHostV1` (via [`build_demo_host`]) and passes its address
//! to `init`. The 4 new function pointers — `kv_get`, `kv_put`,
//! `kv_cas`, `current_stream_id` — are backed by an in-process
//! `HashMap` and a process-global `AtomicU64`. Real Bee uses the
//! raft-replicated KV cluster; this demo is for the S41 Task 3
//! wiring only.

use std::collections::HashMap;
use std::ffi::{CStr, c_char, c_void};
use std::path::Path;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, LazyLock, Mutex};

use bee_plugin_sdk::{
    compute_plugin_id, AbiVersion, BeeHostV1, PluginError, PluginHandle, PluginId, PluginManifest,
    PluginResult,
};
use libloading::{Library, Symbol};
use sha2::{Digest, Sha256};

use crate::PluginManager;

// ---- Demo host state (S41 Task 3) ----
//
// The S41 perf-fib plugin exercises the new `kv_*` and
// `current_stream_id` function pointers on `BeeHostV1`. For the
// in-process `load_library` path, the host backs them with
// process-global state below. Real Bee uses the raft-replicated
// KV cluster; this in-process HashMap is for the S41 Task 3
// wiring only. The `unsafe_code = "allow"` lint at the crate
// level covers the FFI plumbing.

static STREAM_ID_COUNTER: AtomicU64 = AtomicU64::new(0);
static KV_STORE_DEMO: LazyLock<Mutex<HashMap<String, Vec<u8>>>> =
    LazyLock::new(|| Mutex::new(HashMap::new()));

// ---- Demo host FFI (S41 Task 3) ----
//
// Implementations of the 4 new `BeeHostV1` function pointers
// added in Task 2. They read/write the process-global state
// above. The `ctx` parameter is ignored (the plugin SDK contract
// allows the host to use a per-call context, but our demo
// uses a process-global store). Memory returned via `kv_get` is
// leaked via `Box::into_raw`; the plugin is expected to free
// it through a future `host_alloc_free` (out of S41 scope).

/// FFI impl of `kv_get`. On success (rc=0), writes the value's
/// pointer + length to `out_value` / `out_len`. The pointer is
/// a `Box::into_raw`-leaked allocation the caller is expected
/// to free via `host_alloc_free` (TBD). On not-found, returns 1.
/// On invalid args, returns -1.
unsafe extern "C" fn host_kv_get(
    _ctx: *mut c_void,
    key: *const c_char,
    out_value: *mut *mut u8,
    out_len: *mut usize,
) -> i32 {
    if key.is_null() || out_value.is_null() || out_len.is_null() {
        return -1;
    }
    let key_str = match CStr::from_ptr(key).to_str() {
        Ok(s) => s.to_owned(),
        Err(_) => return -1,
    };
    let value_opt = {
        let store = KV_STORE_DEMO.lock().expect("KV_STORE_DEMO poisoned");
        store.get(&key_str).cloned()
    };
    match value_opt {
        Some(v) => {
            let len = v.len();
            let boxed = v.into_boxed_slice();
            let ptr = Box::into_raw(boxed) as *mut u8;
            *out_value = ptr;
            *out_len = len;
            0
        }
        None => 1,
    }
}

/// FFI impl of `kv_put`. Inserts (or overwrites) the value at
/// `key`. Returns 0 on success, -1 on invalid args.
unsafe extern "C" fn host_kv_put(
    _ctx: *mut c_void,
    key: *const c_char,
    value: *const u8,
    len: usize,
) -> i32 {
    if key.is_null() || (value.is_null() && len > 0) {
        return -1;
    }
    let key_str = match CStr::from_ptr(key).to_str() {
        Ok(s) => s.to_owned(),
        Err(_) => return -1,
    };
    let bytes: Vec<u8> = if len == 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(value, len).to_vec()
    };
    KV_STORE_DEMO
        .lock()
        .expect("KV_STORE_DEMO poisoned")
        .insert(key_str, bytes);
    0
}

/// FFI impl of `kv_cas`. Compares the current value at `key` to
/// `expected`; on match, writes `new` and returns 0. On
/// mismatch (including not-found) returns 1. On invalid args
/// returns -1.
unsafe extern "C" fn host_kv_cas(
    _ctx: *mut c_void,
    key: *const c_char,
    expected: *const u8,
    exp_len: usize,
    new: *const u8,
    new_len: usize,
) -> i32 {
    if key.is_null()
        || (expected.is_null() && exp_len > 0)
        || (new.is_null() && new_len > 0)
    {
        return -1;
    }
    let key_str = match CStr::from_ptr(key).to_str() {
        Ok(s) => s.to_owned(),
        Err(_) => return -1,
    };
    let exp_bytes: Vec<u8> = if exp_len == 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(expected, exp_len).to_vec()
    };
    let new_bytes: Vec<u8> = if new_len == 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(new, new_len).to_vec()
    };
    let mut store = KV_STORE_DEMO.lock().expect("KV_STORE_DEMO poisoned");
    let matches = match store.get(&key_str) {
        Some(v) => v == &exp_bytes,
        None => false,
    };
    if matches {
        store.insert(key_str, new_bytes);
        0
    } else {
        1
    }
}

/// FFI impl of `current_stream_id`. Increments a process-global
/// counter, sha256-hashes it, and writes the 32-byte digest to
/// `out_id`. The same counter value always produces the same
/// digest, so the stream_id is stable within a process.
/// Returns 0 on success, -1 on invalid args.
unsafe extern "C" fn host_current_stream_id(
    _ctx: *mut c_void,
    out_id: *mut [u8; 32],
) -> i32 {
    if out_id.is_null() {
        return -1;
    }
    let n = STREAM_ID_COUNTER.fetch_add(1, Ordering::Relaxed);
    let mut hasher = Sha256::new();
    hasher.update(n.to_be_bytes());
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest);
    *out_id = out;
    0
}

/// Construct a real `BeeHostV1` for the demo loader. The 4 new
/// function pointers (`kv_get`, `kv_put`, `kv_cas`,
/// `current_stream_id`) are wired to the FFI implementations
/// above. The 4 existing `register_*_vtable` slots are left as
/// `None` — the S33 mock plugins do not call back into the
/// host, and the S33-deferred registry wiring is out of scope
/// for Task 3.
fn build_demo_host() -> BeeHostV1 {
    BeeHostV1 {
        ctx: std::ptr::null_mut(),
        register_adapter: None,
        register_input_adapter_vtable: None,
        register_output_adapter_vtable: None,
        register_handler_vtable: None,
        kv_get: Some(host_kv_get),
        kv_put: Some(host_kv_put),
        kv_cas: Some(host_kv_cas),
        secret_get: None,
        secret_put: None,
        current_stream_id: Some(host_current_stream_id),
    }
}

/// A plugin loaded from a `cdylib` on disk.
///
/// Owns the [`Library`] (which keeps the `.so` / `.dylib` mapped
/// in memory) and the [`Arc<PluginHandle>`] (the plugin's
/// registered metadata + state). Drop in either order is safe;
/// `LoadedPlugin` is the natural lifetime boundary.
pub struct LoadedPlugin {
    pub id: PluginId,
    pub handle: Arc<PluginHandle>,
    /// The OS handle for the loaded library. Held only to keep
    /// the library mapped while `handle` is alive.
    _lib: Library,
}

impl LoadedPlugin {
    /// The plugin's identity (sha256 of the binary content).
    pub fn id(&self) -> &PluginId {
        &self.id
    }

    /// The plugin's reported manifest (Adapters, Handlers, etc.).
    pub fn manifest(&self) -> &PluginManifest {
        &self.handle.manifest
    }
}

/// Load a `cdylib` plugin from disk.
///
/// Steps:
/// 1. Read the file (for `PluginId` derivation).
/// 2. Open the library with `libloading::Library::new`.
/// 3. Resolve the `bee_plugin_init` symbol.
/// 4. Call it with a real `BeeHostV1` built by
///    [`build_demo_host`] (S41 Task 3: the new `kv_*` and
///    `current_stream_id` function pointers are populated; the
///    S33-deferred `register_*_vtable` slots are `None`).
/// 5. Wrap the returned `*mut PluginHandle` in an `Arc`.
///
/// # Errors
/// - I/O error reading the file → `PluginError::Init`
/// - `libloading` error opening the library → `PluginError::Init`
/// - Missing `bee_plugin_init` symbol → `PluginError::Init`
/// - Plugin's `init()` returned null (init failed) →
///   `PluginError::Init`
pub fn load_library<P: AsRef<Path>>(path: P) -> PluginResult<LoadedPlugin> {
    let path = path.as_ref();
    let content = std::fs::read(path).map_err(|e| {
        PluginError::Init(format!("read {}: {e}", path.display()))
    })?;
    let id = compute_plugin_id(&content);

    unsafe {
        let lib = Library::new(path).map_err(|e| {
            PluginError::Init(format!("dlopen {}: {e}", path.display()))
        })?;
        let init: Symbol<
            unsafe extern "C" fn(*mut BeeHostV1) -> *mut PluginHandle,
        > = lib.get(b"bee_plugin_init").map_err(|e| {
            PluginError::Init(format!(
                "missing bee_plugin_init in {}: {e}",
                path.display()
            ))
        })?;
        let mut host = build_demo_host();
        let host_ptr: *mut BeeHostV1 = &mut host;
        let handle_ptr = init(host_ptr);
        if handle_ptr.is_null() {
            return Err(PluginError::Init(format!(
                "{}: bee_plugin_init returned null",
                path.display()
            )));
        }
        let handle = Arc::from_raw(handle_ptr);
        Ok(LoadedPlugin {
            id,
            handle,
            _lib: lib,
        })
    }
}

/// ABI compatibility check (S20). Returns `Ok(())` if the plugin's
/// declared `abi_version` is in the host's accepted majors.
///
/// Convenience for callers that want to do the check **before**
/// adding the plugin to the `PluginManager`. The
/// `PluginManager::register_library` does the same check
/// internally.
pub fn check_abi(
    manifest: &PluginManifest,
    accepted_majors: &[u32],
) -> PluginResult<()> {
    let abi = AbiVersion::parse(&manifest.abi_version)?;
    if !abi.matches_major(accepted_majors) {
        return Err(PluginError::AbiMismatch {
            path: std::path::PathBuf::from("<unknown — pre-load>"),
            hash: "(unknown — pre-load)".into(),
            claimed: manifest.abi_version.clone(),
            expected: accepted_majors.to_vec(),
            migration_link: bee_plugin_sdk::MIGRATION_DOC_LINK.to_string(),
        });
    }
    Ok(())
}

/// Walk `dir` (non-recursive) and `register_library` every file
/// with the platform's dynamic-library extension
/// (`.so`/`.dylib`/`.dll`). Returns the loaded `PluginId`s in
/// directory-iteration order.
///
/// Errors from individual files (bad ABI, missing symbol, etc.)
/// are collected into the returned `Vec<PluginError>` — one
/// entry per failure. The caller can decide whether to abort or
/// continue. Successfully-loaded plugins are registered with
/// the `PluginManager` regardless of the per-file errors.
///
/// An empty directory (or a directory that contains no files
/// with the dynamic-library extension) returns
/// `(vec![], vec![])` — no error, no load. A missing directory
/// returns an `Init` error describing the read failure.
pub fn load_directory(
    pm: &mut PluginManager,
    dir: &Path,
) -> (Vec<PluginId>, Vec<PluginError>) {
    let mut loaded = vec![];
    let mut errors = vec![];
    let entries = match std::fs::read_dir(dir) {
        Ok(it) => it,
        Err(e) => {
            errors.push(PluginError::Init(format!(
                "read_dir {}: {e}",
                dir.display()
            )));
            return (loaded, errors);
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        let is_lib = matches!(ext, "so" | "dylib" | "dll");
        if !is_lib {
            continue;
        }
        match pm.register_library(&path) {
            Ok(id) => loaded.push(id),
            Err(e) => errors.push(e),
        }
    }
    (loaded, errors)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn check_abi_accepts_v1() {
        let m = PluginManifest {
            name: bee_plugin_sdk::PluginName("test".into()),
            feature_version: "1.0.0".into(),
            abi_version: "v1".into(),
            adapters: vec![],
            handlers: vec![],
        };
        assert!(check_abi(&m, &[1]).is_ok());
        assert!(check_abi(&m, &[1, 2]).is_ok());
        assert!(check_abi(&m, &[2]).is_err());
    }

    #[test]
    fn check_abi_rejects_garbage_version() {
        let m = PluginManifest {
            name: bee_plugin_sdk::PluginName("test".into()),
            feature_version: "1.0.0".into(),
            abi_version: "garbage".into(),
            adapters: vec![],
            handlers: vec![],
        };
        let err = check_abi(&m, &[1]).unwrap_err();
        assert!(matches!(err, PluginError::InvalidAbiVersion(_)));
    }

    #[test]
    fn load_missing_file_errors() {
        let result = load_library("/tmp/this_does_not_exist_xyz.so");
        assert!(matches!(result, Err(PluginError::Init(_))));
    }

    #[test]
    fn load_directory_on_empty_dir_returns_no_errors() {
        let dir = tempfile::tempdir().unwrap();
        let mut pm = crate::PluginManager::new();
        let (loaded, errors) = load_directory(&mut pm, dir.path());
        assert!(loaded.is_empty(), "empty dir must not load anything");
        assert!(errors.is_empty(), "empty dir must not produce errors");
    }
}
