[package]
name = "bee-core"
version = "0.1.0"
authors = ["xiao.huang@enmotech.com <xiao.huang@enmotech.com>"]
edition = "2018"

[dependencies]
url                 = {version = "*"}
parking_lot         = {version = "0.11"}
async-std           = {version = "*"}
log                 = {version = "*"}

#[features]
#default     = [
#    "sql",
#    "sqlplus",
#    "bash",
#    "perl",
#    "sftp",
#    "file",
#    "bssh",
#    "cmd",
#    "agent",
#]
#
#cmd         =   []
#sql         =   ["fallible-iterator", "bincode", "rusqlite","csv"]
#sqlplus     =   []
#bash        =   []
#perl        =   []
#file        =   []
#sftp        =   ["ssh"]
#bssh        =   ["ssh"]
#agent       =   ["heim","humantime","encoding","num_cpus"]

[dev-dependencies]
env_logger = "*"